### ISSUE TITLE
Enable spell checking

### ISSUE THREAD

**Issue by t2d** [systemli/ansible-etherpad#3]
https://www.npmjs.com/package/ep_spellcheck

**Comment by 0x46616c6b** [comment]
For plugins is the option `etherpad_plugins`. So for example

```
etherpad_plugins:
  - spellcheck
```

will install the plugin.

**Comment by t2d** [comment]
Don't you think, it would make sense to provide this as a reasonable default? Or do you want to provide the defaults as defined by the software?

**Comment by 0x46616c6b** [comment]
I would prefer to use the defaults defined by the software. We can also not guarantee that plugins are stable or choose a specific version.
